<?xml version='1.0'?>
<sdf version='1.4' xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_radius" value="0.01"/>
    <xacro:property name="base_height" value="0.15"/> 

    <xacro:property name="box_width" value="0.10"/>
    <xacro:property name="box_depth" value="0.05"/>
    <xacro:property name="box_height" value="0.15"/>

    <xacro:property name="light_radius" value="0.025"/>

    <xacro:macro name="green_mat">
      <material>
          <diffuse>0.00 1.00 0.00 1.00</diffuse>
          <emissive>0.00 1.00 0.00 1.00</emissive>
      </material>
    </xacro:macro>

    <xacro:macro name="red_mat">
      <material>
          <diffuse>0.60 0.60 0.60 1.00</diffuse>
          <emissive>0.00 0.00 0.00 0.00</emissive>
      </material>
    </xacro:macro>

    <xacro:macro name="light" params="color z">
      <link name="${color}">
          <visual name="${color}">
            <pose>0 -${box_depth/2 + 0.005} ${z} 1.57 0 0</pose>
            <geometry>
              <cylinder>
                <radius>${light_radius}</radius>
                <length>0.01</length>
              </cylinder>
            </geometry>
            <xacro:if value="${color == 'green'}">
              <xacro:green_mat/>
            </xacro:if>
            <xacro:if value="${color == 'red'}">
              <xacro:red_mat/>
            </xacro:if>
            <plugin name="${color}_plugin" filename="liblight_plugin.so"/>
          </visual>
        </link>
    </xacro:macro>

    <model name="traffic_light">
        <static>true</static>

        <link name='traffic_light'>
            <pose>0 0 0 0 0 0</pose>
            <visual name='base'>
              <pose>0 0 ${base_height/2} 0 0 0</pose>
              <geometry>
                <cylinder>
                    <radius>${base_radius}</radius>
                    <length>${base_height}</length>
                </cylinder>
              </geometry>
              <material>
                <diffuse>0.25 0.50 0.93 1.00</diffuse>
              </material>
            </visual>
            <visual name='box'>
              <pose>0 0 ${base_height + box_height/2} 0 0 0</pose>
              <geometry>
                <box>
                  <size>${box_width} ${box_depth} ${box_height}</size>
                </box>
              </geometry>
              <material>
                <diffuse>0.89 0.56 0.93 1.00</diffuse>
              </material>                                          
            </visual>            
        </link>

        <xacro:light color="green" z="${base_height + box_height/4}"/>
        <xacro:light color="red" z="${base_height + 3*box_height/4}"/>
    </model>
</sdf>